import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { Sparkles, Activity, Loader2, AlertTriangle, CheckCircle2, Clock } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';

export function AIProjectDashboard({ projectId }: { projectId: string }) {
  const { data: standup, isLoading: loadingStandup, error: errorStandup } = useQuery({
    queryKey: ['ai-standup', projectId],
    queryFn: () => api.get<string>(`/api/ai/report/${projectId}`),
    staleTime: 5 * 60 * 1000,
  });

  const { data: risks, isLoading: loadingRisks, error: errorRisks } = useQuery({
    queryKey: ['ai-risks', projectId],
    queryFn: () => api.get<string>(`/api/ai/risks/${projectId}`),
    staleTime: 5 * 60 * 1000,
  });

  return (
    <div className="p-6 overflow-y-auto h-full space-y-6 bg-muted/10">
      <div className="flex items-center gap-3 mb-4">
        <div className="p-2 bg-indigo-500/10 rounded-lg">
          <Sparkles className="w-6 h-6 text-indigo-500" />
        </div>
        <div>
          <h2 className="text-xl font-bold text-foreground">AI Insights</h2>
          <p className="text-sm text-muted-foreground">Generated by Joino AI Co-pilot</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        
        {/* Daily Standup Report */}
        <Card className="border-indigo-500/20 shadow-md">
          <CardHeader className="bg-indigo-500/5 border-b border-indigo-500/10">
            <CardTitle className="flex items-center gap-2 text-indigo-600">
              <Activity className="w-5 h-5" /> Agile Standup Report
            </CardTitle>
            <CardDescription>Automated daily progress summary for the team.</CardDescription>
          </CardHeader>
          <CardContent className="pt-6">
            {loadingStandup ? (
              <div className="flex flex-col items-center justify-center py-12 text-muted-foreground">
                <Loader2 className="w-8 h-8 animate-spin mb-4 text-indigo-500/50" />
                <p>Analyzing team activity...</p>
              </div>
            ) : errorStandup ? (
              <div className="text-destructive py-4 text-center text-sm">Failed to generate report. Make sure Gemini API Key is configured.</div>
            ) : (
              <div className="prose-custom text-sm text-foreground/80 whitespace-pre-wrap leading-relaxed">
                {standup}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Risk Analysis */}
        <Card className="border-rose-500/20 shadow-md">
          <CardHeader className="bg-rose-500/5 border-b border-rose-500/10">
            <CardTitle className="flex items-center gap-2 text-rose-600">
              <AlertTriangle className="w-5 h-5" /> Red Flag Risk Analysis
            </CardTitle>
            <CardDescription>Predictive overview of blockers and timeline risks.</CardDescription>
          </CardHeader>
          <CardContent className="pt-6">
            {loadingRisks ? (
              <div className="flex flex-col items-center justify-center py-12 text-muted-foreground">
                <Loader2 className="w-8 h-8 animate-spin mb-4 text-rose-500/50" />
                <p>Scanning tasks for bottlenecks...</p>
              </div>
            ) : errorRisks ? (
               <div className="text-destructive py-4 text-center text-sm">Failed to generate risks. Make sure Gemini API Key is configured.</div>
            ) : (
              <div className="prose-custom text-sm text-foreground/80 whitespace-pre-wrap leading-relaxed">
                {risks}
              </div>
            )}
          </CardContent>
        </Card>

      </div>
    </div>
  );
}
